/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Меню для раздела Research
  researchSidebar: [
    {
      type: 'category',
      label: 'Academic Papers',
      collapsible: false,
      items: [
        {
            type: 'autogenerated',
            dirName: '01-research', // Папка docs/01-research
        }
      ],
    },
  ],

  // Меню для раздела Solutions
  solutionsSidebar: [
    {
      type: 'category',
      label: 'Product Portfolio',
      collapsible: false,
      items: [
        {
            type: 'autogenerated',
            dirName: '02-solutions', // Папка docs/02-solutions
        }
      ],
    },
  ],
};

export default sidebars;